### ISSUE TITLE
training data ratio

### ISSUE THREAD

**Issue by m0baxter** [TalSchuster/VitaminC#7]
I have a quick question about the ratio of training data used for the results in Table 4 in the VITAMINC Paper. When you report results for something like "VitC+ MNLI" what do you use all of both datasets? If not what is the ratio, the training script you provide defaults to a sampled 50/50 split, is that what is being reported?

**Comment by TalSchuster** [comment]
Hi, thanks for reaching out. 

Table 4 uses the full training set of the specified tasks. 

Figure 3 presents results of different ratios for combining VitaminC and FEVER with a total training set of 100K examples

**Comment by m0baxter** [comment]
Thanks. To clarify that is equivalent to calling your training script with options like this (we don't care about the rest of the arguments here just the relevant dataset related ones).

```
python scripts/fact_verification.py \
  --tasks_names vitaminc mnli \
  --tasks_ratios -1 -1
```

**Comment by m0baxter** [comment]
I figured it out. Something like this seems to be doing what I want:

```
python scripts/fact_verification.py \
  --tasks_names vitaminc mnli \
  --dataset_size 763355 \ #sum of lengths of vitaminc train and mnli train sets.
  --tasks_ratios 1 -1 \
```
